server.port=8085
spring.application.name= CONFIG-SERVER

spring.cloud.config.server.git.uri=https://github.com/Renukasagayaraj/GitMathDocker
spring.cloud.config.server.git.default-label=main
logging.level.org.springframework.cloud.config=DEBUG

eureka.client.serviceUrl.defaultZone=${EUREKA_SERVER_URL:https://matheditor-be.onrender.com/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

